# Generated by Django 5.1.7 on 2025-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
